### ISSUE TITLE
Not changing default fonts in some apps

### ISSUE THREAD

**Issue by emowpee** [Keinta15/Magisk-iOS-Emoji#77]
Some apps suddenly reverted back to system fonts.

- Facebook
- Messenger
- Whatsapp
- Google Messages

So far those are the apps I've found the issue. All are on their latest update versions and I also tried force stopping and clearing their caches, same with Gboard app. I also tried reflashing the module.

Device:
- Pixel 7 pro
- Feb 2025 security patch
- Magisk Alpha (28102) w/ ZygiskNext 1.2.7

**Comment by Keinta15** [comment]
Emojis won't work in WhatsApp or Google Messages since they have their own emojis embedded. Facebook and Messenger should work unless you update the app. In which case a restart should fix it.

Can you give me the output on 
```
/data/adb/modules/iOS_Emoji/service.log
```
For user convenience I added an action button to run the emoji replacement process that way you wouldn't have to restart your phone but I haven't push a release for it yet.

**Comment by emowpee** [comment]
I already tried restarting but still the same. Not sure what caused this because it just randomly happened. 

I did update my Magisk Alpha using 'Direct Install' though, not sure if that could cause discrepancy. 

Here's the file: [service.log](https://github.com/user-attachments/files/18708628/service.log)

**Comment by emowpee** [comment]
@Keinta15 tried it on my other device with older version of Facebook app, it works properly. I then updated Facebook from Play Store and then went back to Facebook, it indeed reverted back to system default.

**Comment by Keinta15** [comment]
> @Keinta15 tried it on my other device with older version of Facebook app, it works properly. I then updated Facebook from Play Store and then went back to Facebook, it indeed reverted back to system default.

Even after a restart?

**Comment by Keinta15** [comment]
> I already tried restarting but still the same. Not sure what caused this because it just randomly happened. 
> 
> I did update my Magisk Alpha using 'Direct Install' though, not sure if that could cause discrepancy. 
> 
> Here's the file: [service.log](https://github.com/user-attachments/files/18708628/service.log)
> 

Based on the log the Facebook emojis are being replaced properly. Don't know if Magisk Alpha has changed something recently since I use original Magisk

**Comment by emowpee** [comment]
> > [@Keinta15](https://github.com/Keinta15) tried it on my other device with older version of Facebook app, it works properly. I then updated Facebook from Play Store and then went back to Facebook, it indeed reverted back to system default.
> 
> Even after a restart?

Yep, Prolly something changed with latest Facebook and Messenger that interferes with the current implementation of the module. Note that only in keyboard it reverts back to default, the Facebook app and Messenger app itself shows the iOS emoji.

see screenshot:

![Image](https://github.com/user-attachments/assets/b1f253f7-b5fe-42d0-804e-a2f997cca039)

**Comment by Keinta15** [comment]
> > > [@Keinta15](https://github.com/Keinta15) tried it on my other device with older version of Facebook app, it works properly. I then updated Facebook from Play Store and then went back to Facebook, it indeed reverted back to system default.
> > 
> > Even after a restart?
> 
> Yep, Prolly something changed with latest Facebook and Messenger that interferes with the current implementation of the module. Note that only in keyboard it reverts back to default, the Facebook app and Messenger app itself shows the iOS emoji.
> 
> see screenshot:
> 
> ![Image](https://github.com/user-attachments/assets/b1f253f7-b5fe-42d0-804e-a2f997cca039)

Then it's not an issue with the Facebook apps then. It's Google keyboard. 

Hmm what version of Google keyboard are you using?

**Comment by emowpee** [comment]
Gboard 15.0.03.717871796 

![Image](https://github.com/user-attachments/assets/a5071a85-d418-41e6-b8b7-f456a4ecf8bd)

It does work properly with other apps though, here's when I'm using it in Reddit: 

![Image](https://github.com/user-attachments/assets/b71844a2-5137-4a81-87dd-0361260c170d)

**Comment by Keinta15** [comment]
> Gboard 15.0.03.717871796 
> 
> ![Image](https://github.com/user-attachments/assets/a5071a85-d418-41e6-b8b7-f456a4ecf8bd)

That's Gboard beta released today. Alrighty Imma update to that one and see if I can replicate

**Comment by emowpee** [comment]
Thanks, mate!

**Comment by Keinta15** [comment]
> That's Gboard beta released today. Alrighty Imma update to that one and see if I can replicate 
> 

Currently everything is working properly, will keep this issue open to see if anything changes.

![Screenshot_2025-02-07-13-01-05-11_a23b203fd3aafc6dcb84e438dda678b6.jpg](https://github.com/user-attachments/assets/25c38425-cd19-4cb8-90cc-ff7cc7c793b6)

However if you like you could update to this version 

Do clear Gboards cache and once you reboot and everything loads up run the action button in Magisk

**Comment by omer-1080314** [comment]
I have the same issue but only on WhatsApp (emojis in Gboard) 

Version 15.0.03.717871796-beta-arm64-v8a(162031578)

[service.log](https://github.com/user-attachments/files/18817059/service.log)

**Comment by Keinta15** [comment]
> I have the same issue but only on WhatsApp (emojis in Gboard) 
> 
> Version 15.0.03.717871796-beta-arm64-v8a(162031578)
> 
> [service.log](https://github.com/user-attachments/files/18817059/service.log)
> 
> EDIT: Left Gboard beta programme installed version test version of iOS emoji and it works now. I think it really is the beta version acting up. (Maybe reinstalling release zip would also fix in this case)

It's definitely Gboard. Either they're updating the font files or there's a new file I'm not aware of. Weird that it happens in certain apps but not in others. 

I'm still trying to replicate it on my daily use while using the beta.

**Comment by omer-1080314** [comment]
Lol I left the beta programme but now after waking up I see that beta is installed again same version same problem

**Comment by omer-1080314** [comment]
I just switched from Irena Lsposed to jingmatrix Lsposed and now the emoji works in WhatsApp and all other apps (Gboard)

**Comment by emowpee** [comment]
I'm using JingMatrix LSposed this whole time, it's still broken for me

**Comment by wechselgeld** [comment]
I'm facing the same issue. It seems like the issue is the GMS font provider.

My logs are the same as the ones from OP and are only showing this error:
```
GMS font provider not found:
com.google.android.gms/com.google.android.gms.fonts.provider.FontsProvider
GMS font updater not found:
com.google.android.gms.fonts.update.UpdateSchedulerService
```

I can't find the GMS font provider. I've tried to start the service via ADB or find an app - there seems to be no app.
Sadly, I have no clue how to code modules for KSU/Magisk or whatever or else I would help.
